### ISSUE TITLE
User remove from organisation function block 

### ISSUE THREAD

**Issue by uttahb** [appblocks-hub/open_tms#12]
**Add Function block for removing user from organisation in TMS**

**Issue:**
Create a new endpoint `open_tms_remove_org_user` in the backend under the directory `backend/open_tms_remove_org_user` to handle removing user from organisation in the Ticket Management System (TMS).

**Tables:**
- `org_member`
- `org_member_roles`

**Input Signature:**
- **Request Method:** POST
- **Body:**
  ```json
  {
    "org_member_id": "<org_member_id id>"
  }
  ```
- **Is Authenticated:** Yes

**Response Signature:**
- **Success:**
  ```json
  {
    "meta": {
      "status": 200,
      "message": "Removed user from organisation succesfully"
    }
  }
  ```

- **Error in Authentication:**
  ```json
  {
    "meta": {
      "status": 401,
      "message": "Unauthorized access"
    },
    "errors": [
      {
        "code": "AUTH_FAILED",
        "message": "Authentication failed for the request."
      }
    ]
  }
  ```
- **Error with invalid next stage or assignee data:**
  ```json
  {
    "meta": {
      "status": 400,
      "message": "Bad Request"
    },
    "errors": [
      {
        "code": "BAD_REQUESt",
        "message": "Invalid user id"
      }
    ]
  }
  ```
- **Any Other Internal Error:**
  ```json
  {
    "meta": {
      "status": 500,
      "message": "Something went wrong."
    },
    "errors": [
      {
        "code": "INTERNAL_ERROR",
        "message": "Something went wrong."
      }
    ]
  }
  ```

**Expected Workflow:**
1. Authenticate the request and build the user context in the middleware.
2. User needs to be a organisation owner/admin
3. Remove the org_member and org_member_roles accrodingly and if not found return error.
4. upon successful removal send a success response.
8. Capture errors and send appropriate error messages based on the response structure to the frontend.

**Comment by athulya-ratheesh** [comment]
@uttahb I would like to work on this.
