### ISSUE TITLE
Get ticket activity log function block

### ISSUE THREAD

**Issue by uttahb** [appblocks-hub/open_tms#5]
** Add Function block for Listing My Ticket activity log in TMS**

**Issue:**
Create a new endpoint `open_tms_update_ticket` in the backend under the directory `backend/open_tms_list_ticket_activity` to list ticket activity logs for a ticket in the Ticket Management System (TMS).

**Tables:**
- `tickets`
- `ticket_revisions`
- `ticket_activity`

**Input Signature:**
- **Request Method:** GET
- **Parameter:**
  ```
    ticket_id= <ticket id>
  ```
- **Is Authenticated:** Yes

**Response Signature:**
- **Success:**
  ```json
  {
    "meta": {
        "status": 200,
        "message": "Ticket data retrieved successfully"
    },
    "data":[{
      "id": "<ticket_activity_id>",
      "to_stage": {
        "id": "<stage id>",
        "name": "<stage name>"
      },
      "created_dt": "<date of creation>",
      "description": "<activity_description"
    }]
  }
  ```
- **Error in Authentication:**
  ```json
  {
    "status": 401,
    "message": {
      "data": {
        "error": "<auth failed>"
      }
    }
  }
  ```
  **Error with invalid assignee data:**
  ```json
  {
    "meta": {
      "status": 400,
      "message": "Bad Request"
    },
    "errors": [
      {
        "code": "BAD_REQUESt",
        "message": "Assignee is invalid."
      }
    ]
  }
  ```
- **Any Other Internal Error:**
  ```json
  {
    "meta": {
      "status": 500,
      "message": "Something went wrong."
    },
    "errors": [
      {
        "code": "INTERNAL_ERROR",
        "message": "Something went wrong."
      }
    ]
  }
  ```

**Expected Workflow:**
1. Authenticate the request and build the user context in the middleware.
2. Find all the ticket activities by joining ticket, ticket revision and ticket activity tables and get the activities in chronological order.
3. Send to the frontend in an array

**Comment by s-vamshi** [comment]
@uttahb I would like to work on this issue

**Comment by uttahb** [comment]
@s-vamshi Please go ahead and try it out!

**Comment by ittyjose** [comment]
Hey, I am also planning to work on this.

**Comment by uttahb** [comment]
@ittyjose Hi, please go ahead and let us know in case you have any trouble.
